### ISSUE TITLE
v0.2 release checklist

### ISSUE THREAD

**Issue by gorkang** [gorkang/jsPsychMaker#17]
## TESTS
- [x] online
  + [x] standard
  + [x] random_id
  + [x] discarded and readmitted (max_time / accept_discarded)
  + [x] return to protocol after refresh (forced_refresh = true)
- [x] offline
  + [x] standard
  + [x] random_id
  + [x] discarded and readmitted (max_time / accept_discarded)
  + [x] return to protocol after refresh (forced_refresh = true)

## RELEASE
- [x] Update DESCRIPTION AND NEWS in jsPsychMaker, jsPsychMonkeys and jsPsychHelpeR
- [x] Add messages to IndexedDB #16 
- [x] Copy canonical_protocol_DEV to canonical_protocol
- [x] Commit and PUSH all changes in jsPsychR-manual, jsPsychMaker, jsPsychMonkeys and jsPsychHelpeR
- [x] Create release v0.2 in Gthub for jsPsychR-manual, jsPsychMaker, jsPsychMonkeys and jsPsychHelpeR
